In [2]:
from random import random
from functools import reduce
from collections import namedtuple
from queue import  PriorityQueue, SimpleQueue, LifoQueue
import numpy as np

In [47]:
PROBLEM_DIMENSION = 10
NUM_SAMPLES = 20
samples = tuple(np.array([random() < .3 for _ in range(PROBLEM_DIMENSION)]) for _ in range(NUM_SAMPLES))
State = namedtuple('State', ['taken', 'not_taken'])
print(samples)

(array([False,  True,  True, False,  True, False, False, False, False,
       False]), array([False,  True, False,  True, False,  True, False, False, False,
       False]), array([ True, False,  True, False, False, False,  True, False, False,
       False]), array([False, False,  True, False, False,  True, False, False,  True,
       False]), array([False, False, False, False,  True, False, False, False,  True,
        True]), array([False, False,  True, False, False,  True, False,  True, False,
       False]), array([False,  True,  True, False, False,  True, False, False, False,
       False]), array([False, False,  True,  True, False, False, False, False, False,
       False]), array([False,  True, False,  True, False, False, False, False, False,
       False]), array([ True, False,  True, False,  True, False, False, False, False,
        True]), array([False, False, False, False, False,  True, False, False,  True,
       False]), array([ True, False, False, False, False, False, Fals

In [55]:
def goal_check(state: State):
    return np.all(reduce(np.logical_or, [samples[i] for i in state.taken], np.array([False for _ in range(PROBLEM_DIMENSION)])))

def distance_traveled(state: State):
    return len(state.taken)

def distance_from_goal(state: State):
    return PROBLEM_DIMENSION - sum(reduce(np.logical_or, [samples[i] for i in state.taken], np.array([False for _ in range(PROBLEM_DIMENSION)])))

def f_score(state: State):
    return  distance_traveled(state) + distance_from_goal(state)

In [56]:
assert goal_check(State(set(range(NUM_SAMPLES)), set())), "Problem not solvable"

In [57]:
frontier = PriorityQueue()
state: State = State(set(), set(range(NUM_SAMPLES)))
frontier.put((f_score(state), state))

counter = 0
_, current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    for action in current_state.not_taken:
        new_state = State(current_state.taken | {action}, current_state.not_taken - {action})
        frontier.put((f_score(new_state), new_state))
        # print("Frontier:", frontier.queue)
    _, current_state = frontier.get()
    # print("CurrentState:", current_state)
print(f"Solved in {counter} steps")
print(f"State: {current_state}")

Solved in 3 steps
State: State(taken={0, 16, 13}, not_taken={1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 17, 18, 19})


In [58]:
frontier = PriorityQueue()
state: State = State(set(), set(range(NUM_SAMPLES)))
frontier.put((distance_from_goal(state), state))

counter = 0
_, current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    for action in current_state.not_taken:
        new_state = State(current_state.taken | {action}, current_state.not_taken - {action})
        frontier.put((distance_from_goal(new_state), new_state))
        # print("Frontier:", frontier.queue)
    _, current_state = frontier.get()
    # print("CurrentState:", current_state)
print(f"Solved in {counter} steps")
print(f"State: {current_state}")

Solved in 3 steps
State: State(taken={0, 16, 13}, not_taken={1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 17, 18, 19})


In [11]:
[samples[i] for i in current_state.taken]

[array([ True, False, False, False, False,  True,  True, False, False,
        False]),
 array([False,  True,  True,  True, False,  True, False,  True,  True,
         True]),
 array([False,  True, False, False,  True, False, False, False, False,
        False])]

In [14]:
distance_from_goal(current_state)

0

In [15]:
distance_traveled(current_state)

3